# SimpleChatChannels
# `0 = Black  |  `1 = DarkGray
# `2 = GRAY   |  `w = White
# `r = Red    |  `R = DarkRed
# `y = YELLOW |  `Y = Gold
# `g = Green  |  `G = DarkGreen
# `c = Cyan   |  `C = DarkCyan
# `b = Blue   |  `B = DarkBlue
# `p = Purple |  `P = DarkPurple
# `channel = Channel Name
# `player = Player Name
# ChatPrefix - Define the chat prefix for users in a channel
#
ChatPrefix:
  Prefix: '`2[#`channel`2] <`player`2>`w'
